In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [4]:
torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [6]:
y = activation(torch.sum(features * weights) + bias)
y

tensor([[0.1595]])

In [11]:
y = activation((features * weights).sum() + bias)
y

tensor([[0.1595]])

In [13]:
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
y

tensor([[0.1595]])

3-Layer NN

In [16]:
features = torch.randn((1, 3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

w1 = torch.randn(n_input, n_hidden)
w2 = torch.randn(n_hidden, n_output)

B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

3

In [20]:
f_h = activation(torch.mm(features, w1) + B1)
y_h = activation(torch.mm(f_h, w2) + B2)
y_h

tensor([[0.7336]])

Using Numpy

In [21]:
import numpy as np

In [ ]:
a = np.random.rand(4,3)
a